### PR TITLE
Issue with curly brackets

### PR DESCRIPTION
**Pull request by Angelo-Verona**
Framework template file needs to escape curly brackets and add missing

### CODE REVIEW

**Comment by dseira** [comment]
Yes, there is an extra double curly bracket. But there is no need to do this:

```
{% raw %}{{{% endraw %} {{ rundeck_settings.framework.server_uuid }} {% raw %}}}{% endraw %}
```

Just remove the first double curly bracket and it is doen:

```
{{ rundeck_settings.framework.server_uuid }}
```

**Comment by Angelo-Verona** [comment]
That's becuse now is config written nicely without visual change to it from original apart of custom variables fro pillar (Which i prefer). These extra brackets are in original config without salt so should be there after Salt I think.

**Comment by dseira** [comment]
You're right, I didn't remember.

**Comment by dseira** [comment]
Merged. Thanks!

**Pull request merged**
